version: '2'
services:
  app:
    build: .
    image: infoamazonia/visaguas
    ports:
     - 3000:3000
    volumes:
     - ./:/home/node/app
    environment:
      PORT: 3000 
    restart: always 
    networks: 
      - default 
      - weblan
  web:
    build:
      context: ./
      dockerfile: web.dockerfile  
    working_dir:  /home/node/app
    volumes:
      - ./:/home/node/app
      - ./origin.pem:/origin.pem
      - ./origin.key:/origin.key
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - "app"
    networks:
      - weblan
networks: 
 weblan: 
   external:  
    name: ispconfig_weblan 

