version: '2'
services:
  app:
    build: .
    image: infoamazonia/visaguas
    #ports:
    #  - 3001:8000
    environment:
      PORT: 3001 
    restart: always 
    networks: 
      - default 
      - weblan 
 
networks: 
 weblan: 
   external:  
    name: ispconfig_weblan 

