version: '2'
services:
  app:
    build: .
    image: infoamazonia/visaguas
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/app
      - ./docker/local/entrypoint.sh:/entrypoint.sh
    environment:
      PORT: 3000 
    restart: always 
    networks: 
      - default 

